version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npx prisma generate && yarn start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 5s
      retries: 5

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    depends_on:
      app:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "ngrok http 3000 && sleep 15 && node /usr/src/app/setWebhook.js"
    network_mode: "host"

volumes:
  postgres_data:
