version: "3.9"

services:

  db:
    image: postgres:13
    env_file:
      - config/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - config/.env
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - config/.env
    environment:
      - DATABASE_URL=postgresql://admin:postgres@db:5432/magic_chat
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    networks:
      - app-network
    command: /bin/sh -c "npx prisma migrate deploy && npm start"


#  ngrok:
#    image: wernight/ngrok
#    environment:
#      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN} # Get the token on https://ngrok.com
#    depends_on:
#      - app
#    command: ["http", "app:3000"]

volumes:
  postgres_data:
  # node_modules:

networks:
  app-network:
    driver: bridge

