version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOST: db
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["yarn", "start"] # Start the app

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ngrok:
    image: wernight/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN} # Get the token on https://ngrok.com
    depends_on:
      - app
    command: ["http", "app:3000"]

volumes:
  postgres_data:
  node_modules:

